//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIG.VMS.PRESENT {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BIG.VMS.PRESENT.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการออกจากระบบ?.
        /// </summary>
        internal static string LOGOUT {
            get {
                return ResourceManager.GetString("LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is already running..
        /// </summary>
        internal static string MSG_APPLICATION_ALREADLY_RUN {
            get {
                return ResourceManager.GetString("MSG_APPLICATION_ALREADLY_RUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong on appliction, Please contact your Administrator..
        /// </summary>
        internal static string MSG_APPLICATION_FAIL {
            get {
                return ResourceManager.GetString("MSG_APPLICATION_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลบข้อมูลเรียบร้อย.
        /// </summary>
        internal static string MSG_DELETE_COMPLETE {
            get {
                return ResourceManager.GetString("MSG_DELETE_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ต้องการ ลบ ข้อมูล?.
        /// </summary>
        internal static string MSG_DELETE_CONFIRM {
            get {
                return ResourceManager.GetString("MSG_DELETE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ต้องการ ลบ ข้อมูล?.
        /// </summary>
        internal static string MSG_DELETE_CONFIRM_BY {
            get {
                return ResourceManager.GetString("MSG_DELETE_CONFIRM_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถลบข้อมูลได้ .
        /// </summary>
        internal static string MSG_DELETE_INCOMPLETE {
            get {
                return ResourceManager.GetString("MSG_DELETE_INCOMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถลบข้อมูลได้ {0}.
        /// </summary>
        internal static string MSG_DELETE_INCOMPLETE_BY {
            get {
                return ResourceManager.GetString("MSG_DELETE_INCOMPLETE_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระบบทำงานผิดพลาด.
        /// </summary>
        internal static string MSG_ERROR_TITLE {
            get {
                return ResourceManager.GetString("MSG_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระบบเกิดข้อผิดพลาด  กรุณาติดต่อผู้ดูแลระบบ.
        /// </summary>
        internal static string MSG_ERROR_UNKNOWN {
            get {
                return ResourceManager.GetString("MSG_ERROR_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระบบเกิดข้อผิดพลาด {0}.
        /// </summary>
        internal static string MSG_ERROR_UNKNOWN_BY {
            get {
                return ResourceManager.GetString("MSG_ERROR_UNKNOWN_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ออกจากระบบไม่สำเร็จ.
        /// </summary>
        internal static string MSG_LOGOFF_FAIL {
            get {
                return ResourceManager.GetString("MSG_LOGOFF_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ออกจากระบบสำเร็จ.
        /// </summary>
        internal static string MSG_LOGOFF_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_LOGOFF_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการออกจากระบบ?.
        /// </summary>
        internal static string MSG_LOGOUT_QUESTION {
            get {
                return ResourceManager.GetString("MSG_LOGOUT_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบข้อมูล.
        /// </summary>
        internal static string MSG_NOT_FOUND {
            get {
                return ResourceManager.GetString("MSG_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบไฟล์.
        /// </summary>
        internal static string MSG_NOT_FOUND_TARGET_FILE {
            get {
                return ResourceManager.GetString("MSG_NOT_FOUND_TARGET_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบปลายทาง.
        /// </summary>
        internal static string MSG_NOT_FOUND_TARGET_PATH {
            get {
                return ResourceManager.GetString("MSG_NOT_FOUND_TARGET_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แจ้งเตือนการ revise ข้อมูล.
        /// </summary>
        internal static string MSG_REVISE_CONFIRM {
            get {
                return ResourceManager.GetString("MSG_REVISE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บันทึกข้อมูลเรียบร้อย.
        /// </summary>
        internal static string MSG_SAVE_COMPLETE {
            get {
                return ResourceManager.GetString("MSG_SAVE_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ต้องการบันทึกข้อมูล?.
        /// </summary>
        internal static string MSG_SAVE_CONFIRM {
            get {
                return ResourceManager.GetString("MSG_SAVE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ต้องการบันทึกข้อมูล?.
        /// </summary>
        internal static string MSG_SAVE_CONFIRM_BY_KEY {
            get {
                return ResourceManager.GetString("MSG_SAVE_CONFIRM_BY_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถบันทึกข้อมูลได้.
        /// </summary>
        internal static string MSG_SAVE_INCOMPLETE {
            get {
                return ResourceManager.GetString("MSG_SAVE_INCOMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถบันทึกข้อมูลได้  &quot;{0}&quot;.
        /// </summary>
        internal static string MSG_SAVE_INCOMPLETE_BY {
            get {
                return ResourceManager.GetString("MSG_SAVE_INCOMPLETE_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการออกจากระบบ?.
        /// </summary>
        internal static string MSG_SHUTDOWN_SYSTEM {
            get {
                return ResourceManager.GetString("MSG_SHUTDOWN_SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาทำการ login ใหม่.
        /// </summary>
        internal static string MSG_TIME_EXPIRED {
            get {
                return ResourceManager.GetString("MSG_TIME_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุ username และ password.
        /// </summary>
        internal static string MSG_VALIDATE_COMPLELY {
            get {
                return ResourceManager.GetString("MSG_VALIDATE_COMPLELY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุ username และ password.
        /// </summary>
        internal static string MSG_VALIDATE_LOGIN {
            get {
                return ResourceManager.GetString("MSG_VALIDATE_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input number.  &quot;{0}&quot;.
        /// </summary>
        internal static string MSG_VALIDATE_NUMBER_INPUT {
            get {
                return ResourceManager.GetString("MSG_VALIDATE_NUMBER_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ความยาวของของ {0} ต้องไม่เกิน {1} ตัวอักษร.
        /// </summary>
        internal static string MSG_VALIDATE_OVER_LENGTH {
            get {
                return ResourceManager.GetString("MSG_VALIDATE_OVER_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุข้อมูล.
        /// </summary>
        internal static string MSG_VALIDATE_REQ_INPUT {
            get {
                return ResourceManager.GetString("MSG_VALIDATE_REQ_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุข้อมูล {0}.
        /// </summary>
        internal static string MSG_VALIDATE_REQ_INPUT_BY {
            get {
                return ResourceManager.GetString("MSG_VALIDATE_REQ_INPUT_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คำเตือน.
        /// </summary>
        internal static string MSG_WARNING_CAPTION {
            get {
                return ResourceManager.GetString("MSG_WARNING_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เตือน Require Fields.
        /// </summary>
        internal static string MSG_WARNING_REQUIRED_FIELD {
            get {
                return ResourceManager.GetString("MSG_WARNING_REQUIRED_FIELD", resourceCulture);
            }
        }
    }
}
