//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIG.VMS.MODEL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_PROVINCE
    {
        public MAS_PROVINCE()
        {
            this.TRN_APPOINTMENT = new HashSet<TRN_APPOINTMENT>();
            this.TRN_VISITOR = new HashSet<TRN_VISITOR>();
        }
    
        public int AUTO_ID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<TRN_APPOINTMENT> TRN_APPOINTMENT { get; set; }
        public virtual ICollection<TRN_VISITOR> TRN_VISITOR { get; set; }
    }
}
