//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIG.VMS.MODEL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_DEPARTMENT
    {
        public MAS_DEPARTMENT()
        {
            this.MAS_EMPLOYEE = new HashSet<MAS_EMPLOYEE>();
        }
    
        public int AUTO_ID { get; set; }
        public string NAME { get; set; }
        public string SHOW_FLAG { get; set; }
        public Nullable<int> SHOW_SEQ { get; set; }
    
        public virtual ICollection<MAS_EMPLOYEE> MAS_EMPLOYEE { get; set; }
    }
}
