//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIG.VMS.MODEL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_CONFIGURATION
    {
        public int AUTO_ID { get; set; }
        public string MODULE { get; set; }
        public string NAME { get; set; }
        public string VALUE { get; set; }
        public string DESCRIPTION { get; set; }
    }
}
