//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIG.VMS.MODEL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_APPOINTMENT
    {
        public int AUTO_ID { get; set; }
        public string REQUEST_ID_CARD { get; set; }
        public string REQUEST_FIRST_NAME { get; set; }
        public string REQUEST_LAST_NAME { get; set; }
        public string REQUEST_LICENSE_PLATE { get; set; }
        public Nullable<int> REQUEST_LICENSE_PLATE_PROVINCE_ID { get; set; }
        public Nullable<int> REQUEST_CAR_MODEL_ID { get; set; }
        public Nullable<int> CONTACT_EMPLOYEE_ID { get; set; }
        public Nullable<int> REASON_ID { get; set; }
        public Nullable<System.DateTime> CONTACT_DATE { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
    
        public virtual MAS_CAR_MODEL MAS_CAR_MODEL { get; set; }
        public virtual MAS_EMPLOYEE MAS_EMPLOYEE { get; set; }
        public virtual MAS_PROVINCE MAS_PROVINCE { get; set; }
        public virtual MAS_PROVINCE MAS_PROVINCE1 { get; set; }
        public virtual MAS_REASON MAS_REASON { get; set; }
    }
}
